
services:
  postgres:
    image: postgres:16
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
     - 5432:5432
    networks:
      - internal

  web:
    image: nginx:alpine
    container_name: web
    ports: 
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www/project

  php:
    container_name: php
    image: php:8.3.13-fpm-alpine
    build:
      context: ./php/
    networks:
      - internal
    volumes:
      - ../:/var/www/project
    ports:
      - "9000:9000"

networks:
  internal:
    driver: bridge